# This rule is not used by the project kubedredger itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the workshop.golab.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubedredger
    app.kubernetes.io/managed-by: kustomize
  name: configuration-editor-role
rules:
- apiGroups:
  - workshop.golab.io
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workshop.golab.io
  resources:
  - configurations/status
  verbs:
  - get
