---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - workshop.golab.io
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workshop.golab.io
  resources:
  - configurations/finalizers
  verbs:
  - update
- apiGroups:
  - workshop.golab.io
  resources:
  - configurations/status
  verbs:
  - get
  - patch
  - update
